apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-esbfakne
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-esbfakne:11450235768d3dd4b570d7fbdce698b241a88546@sha256:d9a6982ceec457afd9ad2ea4d699fe29f3931a402a502067c514f481e91518b5
          name: container-image
